baseurl = "/"
languageCode = "de-DE"
DefaultContentLanguage = "de"
title = "Mille pattes e.V."
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
pluralizeListTitles = false
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

[params]
  # Sets the meta tag description
  description          = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "Mille pattes e.V."
  # Sets where "View More Posts" links
  viewMorePostLink     = "/blog/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true

  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # set to show or to hide categories in the sidebar
  showSidebarCategories = true

  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"


[social]
  # Email
  email            = "contact@mille-pattes.de"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
  [[languages.de.menu.main]]
        url = "/"
        name = "Home"
        weight = 1
        pre= "fa fa-home"
  [[languages.de.menu.main]]
      url = "/verein"
      name = "Verein"
      weight = 2
      pre= "fa fa-id-card-o"
  [[languages.de.menu.main]]
      url = "/konzept"
      name = "Konzept"
      weight = 3
      pre= "fa fa-newspaper-o"
  [[languages.de.menu.main]]
      url = "/team"
      name = "Team"
      weight = 4
      pre= "fa fa-sitemap"
  [[languages.de.menu.main]]
      url = "/mitglied"
      name = "Mitglied"
      weight = 5
      pre= "fa fa-sitemap"
  [[languages.de.menu.main]]
      url = "/karriere"
      name = "Karriere"
      weight = 6
      pre = "fa fa-list"
  [[languages.de.menu.main]]
      url = "/downloads"
      name = "Download"
      weight = 7
      pre = "fa fa-cloud-download"
  [[languages.de.menu.main]]
      url = "/kontakt"
      name = "Kontakt"
      weight = 8
      pre= "fa fa-envelope-o"


  [languages.fr]
    languageName = "Francais"
    weight = 2
  [[languages.fr.menu.main]]
      url = "/fr"
      name = "Accueil"
      weight = 1
      pre= "fa fa-home"
  [[languages.fr.menu.main]]
      url = "/fr/concept"
      name = "Concept"
      weight = 2
      pre= "fa fa-newspaper-o"
  [[languages.fr.menu.main]]
      url = "/fr/association"
      name = "Association"
      weight = 3
      pre= "fa fa-id-card-o"
  [[languages.fr.menu.main]]
      url = "/fr/equipe"
      name = "Equipe"
      weight = 4
      pre= "fa fa-sitemap"
  [[languages.fr.menu.main]]
      url = "/fr/adhesion"
      name = "Adhésion"
      weight = 5
      pre= "fa fa-sitemap"
  [[languages.fr.menu.main]]
      url = "/fr/carriere"
      name = "Carriere"
      weight = 6
      pre = "fa fa-list"
  [[languages.fr.menu.main]]
      url = "/fr/downloads"
      name = "Download"
      weight = 7
      pre = "fa fa-cloud-download"
  [[languages.fr.menu.main]]
      url = "/fr/contact"
      name = "Contact"
      weight = 8
      pre = "fa fa-envelope-o"

