baseurl = "/"
languageCode = "de-DE"
title = "Mille pattes e.V."
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
pluralizeListTitles = false
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

[params]
  # Sets the meta tag description
  description          = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "Mille pattes e.V."
  # Sets where "View More Posts" links
  viewMorePostLink     = "/blog/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true

  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # set to show or to hide categories in the sidebar
  showSidebarCategories = true

  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"


[social]
  # Email
  email            = "contact@mille-pattes.de"
